//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityAnalyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityAnalyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &quot;async void {0}&quot; to &quot;void {0}&quot; + &quot;async UniTaskVoid {0}&quot;.
        /// </summary>
        internal static string U0001CodeFixTitle {
            get {
                return ResourceManager.GetString("U0001CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string U0001Description {
            get {
                return ResourceManager.GetString("U0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法“{0}”为“async void”方法，会包装为“System.Threading.Tasks.Task”。Unity中请考虑使用“async UniTaskVoid”代替 async void 方法。.
        /// </summary>
        internal static string U0001MessageFormat {
            get {
                return ResourceManager.GetString("U0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回值为空的异步方法.
        /// </summary>
        internal static string U0001Title {
            get {
                return ResourceManager.GetString("U0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string U0002Description {
            get {
                return ResourceManager.GetString("U0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法“{0}”的返回值为“System.Threading.Tasks.Task”，Unity中请考虑使用“Cysharp.Threading.Tasks.UniTask”来代替“System.Threading.Tasks.Task”。.
        /// </summary>
        internal static string U0002MessageFormat {
            get {
                return ResourceManager.GetString("U0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法返回值为System.Threading.Tasks.Task.
        /// </summary>
        internal static string U0002Title {
            get {
                return ResourceManager.GetString("U0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string U0003Description {
            get {
                return ResourceManager.GetString("U0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法“{0}”返回值为&quot;System.Threading.Tasks.Task&lt;Result&gt;&quot;，Unity中请考虑使用“Cysharp.Threading.Tasks.UniTask&lt;Result&gt;”来代替“System.Threading.Tasks.Task”。.
        /// </summary>
        internal static string U0003MessageFormat {
            get {
                return ResourceManager.GetString("U0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法返回值为&quot;Task&lt;TResult&gt;&quot;.
        /// </summary>
        internal static string U0003Title {
            get {
                return ResourceManager.GetString("U0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string U0004Description {
            get {
                return ResourceManager.GetString("U0004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异步匿名隐式构造了“System.Threading.Tasks.Task”。Unity中请考虑使用“Cysharp.Threading.Tasks.UniTask”构造，lambda表达式可以使用“UniTask.Action( async()=&gt;{ } )”或者“UniTask.UnityAction( async ()=&gt;{ } )”方法包装。.
        /// </summary>
        internal static string U0004MessageFormat {
            get {
                return ResourceManager.GetString("U0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异步匿名隐式构造了“System.Threading.Tasks.Task”.
        /// </summary>
        internal static string U0004Title {
            get {
                return ResourceManager.GetString("U0004Title", resourceCulture);
            }
        }
    }
}
