//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to async void方法会包装为一个Task，Unity应中使用 async UniTaskVoid 代替 async void 方法..
        /// </summary>
        internal static string U0001Description {
            get {
                return ResourceManager.GetString("U0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法 {0} 为异步方法，且返回值为空.
        /// </summary>
        internal static string U0001MessageFormat {
            get {
                return ResourceManager.GetString("U0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回值为空的异步方法.
        /// </summary>
        internal static string U0001Title {
            get {
                return ResourceManager.GetString("U0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity中应使用更轻量的 UniTask 代替 Task..
        /// </summary>
        internal static string U0002Description {
            get {
                return ResourceManager.GetString("U0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法 {0} 的返回值为System.Threading.Tasks.Task.
        /// </summary>
        internal static string U0002MessageFormat {
            get {
                return ResourceManager.GetString("U0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法返回值为System.Threading.Tasks.Task.
        /// </summary>
        internal static string U0002Title {
            get {
                return ResourceManager.GetString("U0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity中应使用更轻量的 UniTask&lt;TResult&gt; 代替 Task&lt;TResult&gt;..
        /// </summary>
        internal static string U0003Description {
            get {
                return ResourceManager.GetString("U0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 方法返回值为System.Threading.Tasks.Task&lt;Result&gt;.
        /// </summary>
        internal static string U0003MessageFormat {
            get {
                return ResourceManager.GetString("U0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task&lt;TResult&gt;.
        /// </summary>
        internal static string U0003Title {
            get {
                return ResourceManager.GetString("U0003Title", resourceCulture);
            }
        }
    }
}
